using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace EntKube.Web.Services.Tickets;

/// <summary>
/// What was found in a subject line: which ticket it names, and whether we minted the
/// reference it named it with.
/// </summary>
/// <param name="Number">The ticket number read out of the subject.</param>
/// <param name="Proven">
/// Whether the reference carried a check token that validates. True means this subject was
/// copied from something we sent — a number alone can be typed by anybody, or by mistake.
/// </param>
public readonly record struct SubjectReference(int Number, bool Proven);

/// <summary>
/// The reference a customer is asked to keep in the subject line — <c>[EK-412-K7QX9]</c> —
/// and reading one back out.
///
/// <para><b>Why there is a token on the end.</b> The reference used to be <c>[#412]</c>,
/// read with the pattern <c>#(\d+)</c>, and that cannot tell the reference from any other
/// number somebody writes in a subject. "Order #90210" matched. Worse, a mistyped digit
/// matched too — <c>[#413]</c> is a perfectly good reference to somebody else's ticket, and
/// the reader had no way to doubt it. The token is five characters of a keyed MAC over the
/// number, so a reference either came from us or it did not: a stray number has no token at
/// all, and a changed digit invalidates the one it was copied with.</para>
///
/// <para><b>Why that matters beyond tidiness.</b> A proven reference is a capability. It
/// means the sender is holding something we sent to the people this ticket concerns, which
/// is what makes it safe to act on a reply without a person reading it first — see
/// <see cref="Mail.ArrivalPolicy"/>. An unproven number still finds its ticket exactly as it
/// always did; it just goes to the queue for somebody to confirm.</para>
///
/// <para><b>Why the number is not scoped to the customer.</b> It was tempting, and it is
/// wrong twice over. Numbers are allocated across the installation, so two customers cannot
/// collide on one and a customer code protects nothing. And a ticket can be moved to another
/// customer, which would invalidate every reference already sitting in the reporter's mailbox
/// — the one thing a reference exists to survive.</para>
///
/// <para><b>Why the old format still reads.</b> Every receipt sent before this existed said
/// <c>[#412]</c>, and those tickets are still open. A bare number is therefore still
/// understood, and still reaches its ticket; it simply arrives unproven, which is the
/// behaviour everything had before. No backfill, and nothing to migrate.</para>
/// </summary>
public partial class TicketReference
{
    /// <summary>
    /// Crockford's base 32: no I, L, O or U, so nothing in a token can be read as a
    /// different character by somebody retyping it off a phone screen.
    /// </summary>
    private const string Alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

    /// <summary>
    /// How long the token is. Five characters of this alphabet is a little over 33 million,
    /// which is far past guessing — and being wrong costs nothing anyway, since an
    /// unrecognised token means the message waits for a person rather than being refused.
    /// </summary>
    private const int TokenLength = 5;

    private readonly byte[] key;

    /// <summary>
    /// Derives the signing key from the platform root key.
    /// </summary>
    /// <param name="rootKey">
    /// <c>Vault:RootKey</c> — required at startup, stable for the life of the installation,
    /// and never regenerated by the installer, which is what makes a reference we sent last
    /// year still validate today.
    /// </param>
    /// <remarks>
    /// Derived rather than used directly, so that this and the vault cannot be made to sign
    /// or decrypt for each other. Rotating the root key invalidates tokens minted under the
    /// old one; those references fall back to being read as bare numbers, which is a
    /// degradation to the previous behaviour rather than a breakage.
    /// </remarks>
    public TicketReference(byte[] rootKey)
    {
        ArgumentNullException.ThrowIfNull(rootKey);

        key = HKDF.DeriveKey(
            HashAlgorithmName.SHA256,
            rootKey,
            outputLength: 32,
            info: Encoding.UTF8.GetBytes("entkube:ticket-reference:v1"));
    }

    /// <summary>
    /// The reference for a ticket, as it goes into a subject line and is quoted in the body
    /// of the receipt.
    /// </summary>
    public string For(int number) =>
        string.Create(CultureInfo.InvariantCulture, $"[EK-{number}-{Token(number)}]");

    /// <summary>
    /// The ticket a subject line names, or null when it names none.
    ///
    /// <para>The full form is looked for across the whole subject before the bare number is
    /// considered, so a subject carrying both — "Order #90210 — re: [EK-412-K7QX9]" — is read
    /// as the ticket it is about rather than as whichever number happens to come first.</para>
    /// </summary>
    public SubjectReference? InSubject(string? subject)
    {
        if (string.IsNullOrWhiteSpace(subject))
        {
            return null;
        }

        if (Full().Match(subject) is { Success: true } full
            && int.TryParse(
                full.Groups[1].Value, NumberStyles.None, CultureInfo.InvariantCulture,
                out int signed))
        {
            return new SubjectReference(
                signed,
                Proven: string.Equals(
                    full.Groups[2].Value, Token(signed), StringComparison.OrdinalIgnoreCase));
        }

        return Legacy().Match(subject) is { Success: true } legacy
            && int.TryParse(
                legacy.Groups[1].Value, NumberStyles.None, CultureInfo.InvariantCulture,
                out int bare)
            ? new SubjectReference(bare, Proven: false)
            : null;
    }

    /// <summary>
    /// The ticket a subject proves it is about, or null when it does not prove anything.
    /// What the decision to act without a person reading the message first rests on.
    /// </summary>
    public int? ProvenIn(string? subject) =>
        InSubject(subject) is { Proven: true } reference ? reference.Number : null;

    /// <summary>
    /// The check token for a number: the first <see cref="TokenLength"/> characters' worth of
    /// a MAC over it, in the alphabet above. Truncated deliberately — a subject line has to
    /// survive being read aloud and retyped, and the whole digest would not be.
    /// </summary>
    private string Token(int number)
    {
        byte[] mac = HMACSHA256.HashData(
            key,
            Encoding.UTF8.GetBytes(
                string.Create(CultureInfo.InvariantCulture, $"ticket:{number}")));

        // Five characters is 25 bits, taken from the low end of the first four bytes.
        uint bits = BitConverter.ToUInt32(mac, 0) & 0x01FFFFFF;

        return string.Create(TokenLength, bits, static (span, value) =>
        {
            for (int i = span.Length - 1; i >= 0; i--)
            {
                span[i] = Alphabet[(int)(value % 32)];
                value /= 32;
            }
        });
    }

    // The brackets are not required: a client that strips them, or a person quoting the
    // reference in a sentence, is still understood. What is required is that the three parts
    // are not part of a longer run of the same characters, so a reference is never read out
    // of the middle of some other identifier.
    [GeneratedRegex(
        @"(?<![A-Za-z0-9])EK-(\d{1,9})-([0-9A-Za-z]{5})(?![A-Za-z0-9])",
        RegexOptions.IgnoreCase)]
    private static partial Regex Full();

    [GeneratedRegex(@"#(\d{1,9})")]
    private static partial Regex Legacy();
}
