// <auto-generated />
using EntKube.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EntKube.Web.Data.Migrations.Sqlite
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615100000_AddNotificationChannelFilters")]
    partial class AddNotificationChannelFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty — model snapshot is maintained in ApplicationDbContextModelSnapshot.cs.
        }
    }
}
