// <auto-generated />
using EntKube.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EntKube.Web.Data.Migrations.Sqlite
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614120000_AddDeploymentRouteRewritePath")]
    partial class AddDeploymentRouteRewritePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty — model snapshot is maintained in ApplicationDbContextModelSnapshot.cs.
            // EF Core does not call BuildTargetModel at runtime; it is only used by the dotnet-ef tooling
            // when scaffolding the NEXT migration, which should be done via dotnet ef migrations add.
        }
    }
}
