// <auto-generated />
using System;
using EntKube.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntKube.Web.Data.Migrations.Sqlite
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526053758_AddHarborComponentConfig")]
    partial class AddHarborComponentConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EntKube.Web.Data.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("EntKube.Web.Data.AppDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmChartName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmChartVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmRepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("AppDeployments");
                });

            modelBuilder.Entity("EntKube.Web.Data.AppEnvironment", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("AppEnvironments");
                });

            modelBuilder.Entity("EntKube.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntKube.Web.Data.ClusterComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmChartName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmChartVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmRepoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HelmValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Name")
                        .IsUnique();

                    b.ToTable("ClusterComponents");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CnpgClusterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CnpgClusterId", "Name")
                        .IsUnique();

                    b.ToTable("CnpgBackups");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Instances")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KubernetesClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostgresVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageLinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("KubernetesClusterId", "Name", "Namespace")
                        .IsUnique();

                    b.ToTable("CnpgClusters");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CnpgClusterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CnpgClusterId", "Name")
                        .IsUnique();

                    b.ToTable("CnpgDatabases");
                });

            modelBuilder.Entity("EntKube.Web.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EntKube.Web.Data.CustomerAccess", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAccesses");
                });

            modelBuilder.Entity("EntKube.Web.Data.DatabaseBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CnpgDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KubernetesSecretName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MongoDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegisteredPostgresDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppDeploymentId");

                    b.HasIndex("CnpgDatabaseId");

                    b.HasIndex("MongoDatabaseId");

                    b.HasIndex("RegisteredPostgresDatabaseId");

                    b.ToTable("DatabaseBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.DeploymentManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("YamlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.ToTable("DeploymentManifests");
                });

            modelBuilder.Entity("EntKube.Web.Data.DeploymentResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("ParentResourceId");

                    b.ToTable("DeploymentResources");
                });

            modelBuilder.Entity("EntKube.Web.Data.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("EntKube.Web.Data.ExternalRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterIssuerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayNamespace")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TlsCertificate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsPrivateKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ExternalRoutes");
                });

            modelBuilder.Entity("EntKube.Web.Data.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EntKube.Web.Data.GroupMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("EntKube.Web.Data.HarborComponentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClusterComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CnpgDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterComponentId");

                    b.HasIndex("CnpgDatabaseId");

                    b.HasIndex("StorageLinkId");

                    b.HasIndex("TenantId");

                    b.ToTable("HarborComponentConfigs");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeycloakRealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakRealmId");

                    b.HasIndex("StorageLinkId");

                    b.ToTable("KeycloakBackups");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakComponentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClusterComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CnpgDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegisteredPostgresDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterComponentId");

                    b.HasIndex("CnpgDatabaseId");

                    b.HasIndex("RegisteredPostgresDatabaseId");

                    b.HasIndex("TenantId");

                    b.ToTable("KeycloakComponentConfigs");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakRealm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountTheme")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KeycloakComponentConfigId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KeycloakThemeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedAppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginTheme")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakThemeId");

                    b.HasIndex("LinkedAppId");

                    b.HasIndex("KeycloakComponentConfigId", "RealmName")
                        .IsUnique();

                    b.ToTable("KeycloakRealms");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountTheme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeycloakComponentConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginTheme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakComponentConfigId", "Name")
                        .IsUnique();

                    b.ToTable("KeycloakThemes");
                });

            modelBuilder.Entity("EntKube.Web.Data.KubernetesCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiServerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kubeconfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("KubernetesClusters");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MongoClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MongoClusterId", "Name")
                        .IsUnique();

                    b.ToTable("MongoBackups");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KubernetesClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("Members")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MongoVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageLinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("KubernetesClusterId", "Name", "Namespace")
                        .IsUnique();

                    b.ToTable("MongoClusters");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MongoClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MongoClusterId", "Name")
                        .IsUnique();

                    b.ToTable("MongoDatabases");
                });

            modelBuilder.Entity("EntKube.Web.Data.OpenStackConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDomainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDomainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("OpenStackConnections");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegisteredPostgresInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredPostgresInstanceId", "Name")
                        .IsUnique();

                    b.ToTable("RegisteredPostgresDatabases");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresDump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegisteredPostgresDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredPostgresDatabaseId");

                    b.HasIndex("StorageLinkId");

                    b.ToTable("RegisteredPostgresDumps");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPodName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KubernetesClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KubernetesClusterId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("RegisteredPostgresInstances");
                });

            modelBuilder.Entity("EntKube.Web.Data.SecretVault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedDataKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("SecretVaults");
                });

            modelBuilder.Entity("EntKube.Web.Data.StorageBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KubernetesSecretName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppDeploymentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("StorageLinkId");

                    b.ToTable("StorageBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.StorageLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpenStackConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("OpenStackConnectionId");

                    b.HasIndex("TenantId");

                    b.ToTable("StorageLinks");
                });

            modelBuilder.Entity("EntKube.Web.Data.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("EntKube.Web.Data.TenantMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantMemberships");
                });

            modelBuilder.Entity("EntKube.Web.Data.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("TenantRoles");
                });

            modelBuilder.Entity("EntKube.Web.Data.VaultSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CnpgClusterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CnpgDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("KubernetesNamespace")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("KubernetesSecretName")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MongoClusterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MongoDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("OpenStackConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegisteredPostgresDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StorageLinkId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncToKubernetes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("CnpgClusterId");

                    b.HasIndex("CnpgDatabaseId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("MongoClusterId");

                    b.HasIndex("MongoDatabaseId");

                    b.HasIndex("RegisteredPostgresDatabaseId");

                    b.HasIndex("StorageLinkId");

                    b.HasIndex("VaultId", "AppId", "Name")
                        .IsUnique();

                    b.HasIndex("VaultId", "ComponentId", "Name")
                        .IsUnique();

                    b.ToTable("VaultSecrets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntKube.Web.Data.App", b =>
                {
                    b.HasOne("EntKube.Web.Data.Customer", "Customer")
                        .WithMany("Apps")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EntKube.Web.Data.AppDeployment", b =>
                {
                    b.HasOne("EntKube.Web.Data.App", "App")
                        .WithMany("Deployments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.KubernetesCluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Cluster");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("EntKube.Web.Data.AppEnvironment", b =>
                {
                    b.HasOne("EntKube.Web.Data.App", "App")
                        .WithMany("AppEnvironments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.Environment", "Environment")
                        .WithMany("AppEnvironments")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("EntKube.Web.Data.ClusterComponent", b =>
                {
                    b.HasOne("EntKube.Web.Data.KubernetesCluster", "Cluster")
                        .WithMany("Components")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgBackup", b =>
                {
                    b.HasOne("EntKube.Web.Data.CnpgCluster", "CnpgCluster")
                        .WithMany("Backups")
                        .HasForeignKey("CnpgClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnpgCluster");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgCluster", b =>
                {
                    b.HasOne("EntKube.Web.Data.KubernetesCluster", "KubernetesCluster")
                        .WithMany()
                        .HasForeignKey("KubernetesClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KubernetesCluster");

                    b.Navigation("StorageLink");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgDatabase", b =>
                {
                    b.HasOne("EntKube.Web.Data.CnpgCluster", "CnpgCluster")
                        .WithMany("Databases")
                        .HasForeignKey("CnpgClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnpgCluster");
                });

            modelBuilder.Entity("EntKube.Web.Data.Customer", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.CustomerAccess", b =>
                {
                    b.HasOne("EntKube.Web.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntKube.Web.Data.DatabaseBinding", b =>
                {
                    b.HasOne("EntKube.Web.Data.AppDeployment", "AppDeployment")
                        .WithMany("DatabaseBindings")
                        .HasForeignKey("AppDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.CnpgDatabase", "CnpgDatabase")
                        .WithMany("DatabaseBindings")
                        .HasForeignKey("CnpgDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.MongoDatabase", "MongoDatabase")
                        .WithMany("DatabaseBindings")
                        .HasForeignKey("MongoDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.RegisteredPostgresDatabase", "RegisteredPostgresDatabase")
                        .WithMany("DatabaseBindings")
                        .HasForeignKey("RegisteredPostgresDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppDeployment");

                    b.Navigation("CnpgDatabase");

                    b.Navigation("MongoDatabase");

                    b.Navigation("RegisteredPostgresDatabase");
                });

            modelBuilder.Entity("EntKube.Web.Data.DeploymentManifest", b =>
                {
                    b.HasOne("EntKube.Web.Data.AppDeployment", "Deployment")
                        .WithMany("Manifests")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("EntKube.Web.Data.DeploymentResource", b =>
                {
                    b.HasOne("EntKube.Web.Data.AppDeployment", "Deployment")
                        .WithMany("Resources")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.DeploymentResource", "ParentResource")
                        .WithMany("ChildResources")
                        .HasForeignKey("ParentResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Deployment");

                    b.Navigation("ParentResource");
                });

            modelBuilder.Entity("EntKube.Web.Data.Environment", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("Environments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.ExternalRoute", b =>
                {
                    b.HasOne("EntKube.Web.Data.ClusterComponent", "Component")
                        .WithMany("ExternalRoutes")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("EntKube.Web.Data.Group", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("Groups")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.GroupMembership", b =>
                {
                    b.HasOne("EntKube.Web.Data.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntKube.Web.Data.HarborComponentConfig", b =>
                {
                    b.HasOne("EntKube.Web.Data.ClusterComponent", "ClusterComponent")
                        .WithMany()
                        .HasForeignKey("ClusterComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.CnpgDatabase", "CnpgDatabase")
                        .WithMany()
                        .HasForeignKey("CnpgDatabaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterComponent");

                    b.Navigation("CnpgDatabase");

                    b.Navigation("StorageLink");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakBackup", b =>
                {
                    b.HasOne("EntKube.Web.Data.KeycloakRealm", "Realm")
                        .WithMany("Backups")
                        .HasForeignKey("KeycloakRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Realm");

                    b.Navigation("StorageLink");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakComponentConfig", b =>
                {
                    b.HasOne("EntKube.Web.Data.ClusterComponent", "ClusterComponent")
                        .WithMany()
                        .HasForeignKey("ClusterComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.CnpgDatabase", "CnpgDatabase")
                        .WithMany()
                        .HasForeignKey("CnpgDatabaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.RegisteredPostgresDatabase", "RegisteredPostgresDatabase")
                        .WithMany()
                        .HasForeignKey("RegisteredPostgresDatabaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterComponent");

                    b.Navigation("CnpgDatabase");

                    b.Navigation("RegisteredPostgresDatabase");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakRealm", b =>
                {
                    b.HasOne("EntKube.Web.Data.KeycloakComponentConfig", "ComponentConfig")
                        .WithMany("Realms")
                        .HasForeignKey("KeycloakComponentConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.KeycloakTheme", "Theme")
                        .WithMany("Realms")
                        .HasForeignKey("KeycloakThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.App", "LinkedApp")
                        .WithMany()
                        .HasForeignKey("LinkedAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ComponentConfig");

                    b.Navigation("LinkedApp");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakTheme", b =>
                {
                    b.HasOne("EntKube.Web.Data.KeycloakComponentConfig", "ComponentConfig")
                        .WithMany()
                        .HasForeignKey("KeycloakComponentConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentConfig");
                });

            modelBuilder.Entity("EntKube.Web.Data.KubernetesCluster", b =>
                {
                    b.HasOne("EntKube.Web.Data.Environment", "Environment")
                        .WithMany("KubernetesClusters")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("KubernetesClusters")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoBackup", b =>
                {
                    b.HasOne("EntKube.Web.Data.MongoCluster", "MongoCluster")
                        .WithMany("Backups")
                        .HasForeignKey("MongoClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MongoCluster");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoCluster", b =>
                {
                    b.HasOne("EntKube.Web.Data.KubernetesCluster", "KubernetesCluster")
                        .WithMany()
                        .HasForeignKey("KubernetesClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KubernetesCluster");

                    b.Navigation("StorageLink");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoDatabase", b =>
                {
                    b.HasOne("EntKube.Web.Data.MongoCluster", "MongoCluster")
                        .WithMany("Databases")
                        .HasForeignKey("MongoClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MongoCluster");
                });

            modelBuilder.Entity("EntKube.Web.Data.OpenStackConnection", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresDatabase", b =>
                {
                    b.HasOne("EntKube.Web.Data.RegisteredPostgresInstance", "RegisteredPostgresInstance")
                        .WithMany("Databases")
                        .HasForeignKey("RegisteredPostgresInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredPostgresInstance");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresDump", b =>
                {
                    b.HasOne("EntKube.Web.Data.RegisteredPostgresDatabase", "RegisteredPostgresDatabase")
                        .WithMany()
                        .HasForeignKey("RegisteredPostgresDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredPostgresDatabase");

                    b.Navigation("StorageLink");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresInstance", b =>
                {
                    b.HasOne("EntKube.Web.Data.KubernetesCluster", "KubernetesCluster")
                        .WithMany()
                        .HasForeignKey("KubernetesClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KubernetesCluster");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.SecretVault", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithOne("Vault")
                        .HasForeignKey("EntKube.Web.Data.SecretVault", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.StorageBinding", b =>
                {
                    b.HasOne("EntKube.Web.Data.AppDeployment", "AppDeployment")
                        .WithMany("StorageBindings")
                        .HasForeignKey("AppDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.ClusterComponent", "Component")
                        .WithMany("StorageBindings")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany("StorageBindings")
                        .HasForeignKey("StorageLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppDeployment");

                    b.Navigation("Component");

                    b.Navigation("StorageLink");
                });

            modelBuilder.Entity("EntKube.Web.Data.StorageLink", b =>
                {
                    b.HasOne("EntKube.Web.Data.ClusterComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("EntKube.Web.Data.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.OpenStackConnection", "OpenStackConnection")
                        .WithMany("StorageLinks")
                        .HasForeignKey("OpenStackConnectionId");

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Environment");

                    b.Navigation("OpenStackConnection");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.TenantMembership", b =>
                {
                    b.HasOne("EntKube.Web.Data.TenantRole", "Role")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntKube.Web.Data.TenantRole", b =>
                {
                    b.HasOne("EntKube.Web.Data.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EntKube.Web.Data.VaultSecret", b =>
                {
                    b.HasOne("EntKube.Web.Data.App", "App")
                        .WithMany("Secrets")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.CnpgCluster", "CnpgCluster")
                        .WithMany()
                        .HasForeignKey("CnpgClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.CnpgDatabase", "CnpgDatabase")
                        .WithMany()
                        .HasForeignKey("CnpgDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.ClusterComponent", "Component")
                        .WithMany("Secrets")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.MongoCluster", "MongoCluster")
                        .WithMany()
                        .HasForeignKey("MongoClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.MongoDatabase", "MongoDatabase")
                        .WithMany()
                        .HasForeignKey("MongoDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.RegisteredPostgresDatabase", "RegisteredPostgresDatabase")
                        .WithMany()
                        .HasForeignKey("RegisteredPostgresDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntKube.Web.Data.StorageLink", "StorageLink")
                        .WithMany()
                        .HasForeignKey("StorageLinkId");

                    b.HasOne("EntKube.Web.Data.SecretVault", "Vault")
                        .WithMany("Secrets")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("CnpgCluster");

                    b.Navigation("CnpgDatabase");

                    b.Navigation("Component");

                    b.Navigation("MongoCluster");

                    b.Navigation("MongoDatabase");

                    b.Navigation("RegisteredPostgresDatabase");

                    b.Navigation("StorageLink");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EntKube.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EntKube.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntKube.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EntKube.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntKube.Web.Data.App", b =>
                {
                    b.Navigation("AppEnvironments");

                    b.Navigation("Deployments");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("EntKube.Web.Data.AppDeployment", b =>
                {
                    b.Navigation("DatabaseBindings");

                    b.Navigation("Manifests");

                    b.Navigation("Resources");

                    b.Navigation("StorageBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.ClusterComponent", b =>
                {
                    b.Navigation("ExternalRoutes");

                    b.Navigation("Secrets");

                    b.Navigation("StorageBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgCluster", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("Databases");
                });

            modelBuilder.Entity("EntKube.Web.Data.CnpgDatabase", b =>
                {
                    b.Navigation("DatabaseBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.Customer", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("EntKube.Web.Data.DeploymentResource", b =>
                {
                    b.Navigation("ChildResources");
                });

            modelBuilder.Entity("EntKube.Web.Data.Environment", b =>
                {
                    b.Navigation("AppEnvironments");

                    b.Navigation("KubernetesClusters");
                });

            modelBuilder.Entity("EntKube.Web.Data.Group", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakComponentConfig", b =>
                {
                    b.Navigation("Realms");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakRealm", b =>
                {
                    b.Navigation("Backups");
                });

            modelBuilder.Entity("EntKube.Web.Data.KeycloakTheme", b =>
                {
                    b.Navigation("Realms");
                });

            modelBuilder.Entity("EntKube.Web.Data.KubernetesCluster", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoCluster", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("Databases");
                });

            modelBuilder.Entity("EntKube.Web.Data.MongoDatabase", b =>
                {
                    b.Navigation("DatabaseBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.OpenStackConnection", b =>
                {
                    b.Navigation("StorageLinks");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresDatabase", b =>
                {
                    b.Navigation("DatabaseBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.RegisteredPostgresInstance", b =>
                {
                    b.Navigation("Databases");
                });

            modelBuilder.Entity("EntKube.Web.Data.SecretVault", b =>
                {
                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("EntKube.Web.Data.StorageLink", b =>
                {
                    b.Navigation("StorageBindings");
                });

            modelBuilder.Entity("EntKube.Web.Data.Tenant", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Environments");

                    b.Navigation("Groups");

                    b.Navigation("KubernetesClusters");

                    b.Navigation("Memberships");

                    b.Navigation("Roles");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("EntKube.Web.Data.TenantRole", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
