using System.Globalization;
using System.Text.RegularExpressions;

namespace EntKube.Web.Services.Mail;

/// <summary>
/// The Message-Id we stamp on mail we send about a ticket, and reading a ticket number
/// back out of one.
///
/// <para><b>Why the number is in the identifier.</b> A reply quotes what it is replying to
/// in <c>In-Reply-To</c> and <c>References</c>, and those survive everything a subject
/// line does not: a client that rewrites "Re:", a person who edits the subject, a forward
/// that strips it. Putting the ticket number in the id we send means a reply can be placed
/// on its ticket with no lookup table and nothing stored — the thread carries the answer
/// back to us.</para>
///
/// <para><b>Why both halves live here.</b> The format was a string literal in the sender
/// and a comment claiming the reader understood it. The reader did not, so a reply with a
/// mangled subject opened a second ticket about the fault already being worked — the exact
/// case the comment said was covered. One place now writes the format and reads it, so
/// they cannot disagree again.</para>
/// </summary>
public static partial class SupportMessageId
{
    /// <summary>The right-hand side used before one was derived from the sender.</summary>
    /// <remarks>
    /// Still read, and always will be: every ticket opened before this carries it in the
    /// inbox of the person who reported it, and their reply is threaded by it.
    /// </remarks>
    public const string LegacyDomain = "entkube";

    /// <summary>
    /// The identifier for a message we are sending about a ticket. Unique per message: the
    /// same ticket sends several, and two sharing an id would make a mess of any client
    /// that threads properly.
    /// </summary>
    /// <param name="ticketNumber">The ticket it is about.</param>
    /// <param name="fromAddress">
    /// The address the message is sent from, whose domain becomes the right-hand side.
    ///
    /// <para><b>Why this is not a constant any more.</b> It used to be the bare word
    /// <c>entkube</c>, which is not a domain — nothing resolves it and nothing can ever be
    /// published for it. A Message-Id whose right-hand side is not a hostname, and does not
    /// match the From domain, is one of the oldest and cheapest signals a filter has that a
    /// message was generated by something that does not send much mail; it costs points at
    /// exactly the moment a receipt is being judged by a mailbox that has never heard of us.
    /// RFC 5322 asks for a globally unique identifier and every well-behaved sender builds
    /// one from a domain it owns.</para>
    ///
    /// <para>Null or unparseable falls back to the old word rather than inventing a domain.
    /// A receipt that threads is worth more than one that scores well.</para>
    /// </param>
    public static string For(int ticketNumber, string? fromAddress = null) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"ticket-{ticketNumber}.{Guid.NewGuid():N}@{DomainOf(fromAddress)}");

    /// <summary>
    /// The domain half of an address, lower-cased, or <see cref="LegacyDomain"/> when there
    /// is nothing usable to take one from.
    /// </summary>
    private static string DomainOf(string? address)
    {
        if (string.IsNullOrWhiteSpace(address))
        {
            return LegacyDomain;
        }

        int at = address.LastIndexOf('@');

        if (at < 0 || at == address.Length - 1)
        {
            return LegacyDomain;
        }

        string domain = address[(at + 1)..].Trim().Trim('>').ToLowerInvariant();

        // A domain with no dot is no better than the word it replaces, and a space means
        // this was never an address.
        return domain.Contains('.', StringComparison.Ordinal)
               && !domain.Any(char.IsWhiteSpace)
            ? domain
            : LegacyDomain;
    }

    /// <summary>
    /// The ticket number in one of our identifiers, or null when it is not one of ours.
    ///
    /// <para>Only ours are read: the shape is <c>ticket-N.</c> followed by exactly
    /// thirty-two hex digits, which nothing else produces. A reply whose <c>In-Reply-To</c>
    /// points at a colleague's message must not be mined for a number that happens to look
    /// like one.</para>
    ///
    /// <para><b>Any domain is accepted, and that is deliberate.</b> The right-hand side is
    /// now the sending address's domain, which changes when a tenant changes its support
    /// address — and every identifier already in a customer's mailbox keeps the one it was
    /// sent with, including the bare <see cref="LegacyDomain"/> from before there was a
    /// better answer. Threading has to survive both, so the shape is what identifies ours
    /// rather than the domain.</para>
    ///
    /// <para><b>What the random half is and is not.</b> It makes two messages about one
    /// ticket distinct, which is all a mail client needs. It is <em>not</em> checked against
    /// anything stored, so it is not a secret and reading a number out of a crafted header
    /// is possible for anyone who knows a ticket number. That is bounded by what a threaded
    /// match can do: it puts a suggestion in front of a person, who accepts it by name. It
    /// is not enough to build anything on that assumes only the recipients of our mail can
    /// produce one.</para>
    /// </summary>
    public static int? TicketNumberIn(string? messageId)
    {
        if (string.IsNullOrWhiteSpace(messageId))
        {
            return null;
        }

        Match match = Ours().Match(messageId.Trim().Trim('<', '>'));

        return match.Success
            && int.TryParse(
                match.Groups[1].Value, NumberStyles.None, CultureInfo.InvariantCulture, out int number)
            ? number
            : null;
    }

    /// <summary>
    /// Finds the first of our identifiers in a thread's chain, so a long conversation is
    /// still placed on its ticket when the immediate parent was somebody else's message.
    /// </summary>
    public static string? OursIn(IEnumerable<string?> messageIds) =>
        messageIds.FirstOrDefault(id => TicketNumberIn(id) is not null);

    // The domain is anything that looks like one, for the reason given on TicketNumberIn:
    // identifiers already sent carry whatever domain was in force when they went out, and
    // the shape is what makes one ours.
    [GeneratedRegex(
        @"^ticket-(\d{1,9})\.[0-9a-f]{32}@[A-Za-z0-9.\-]+$", RegexOptions.IgnoreCase)]
    private static partial Regex Ours();
}
