using EntKube.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace EntKube.Web.Services;

public class AppL4RouteRequest
{
    public L4Protocol Protocol { get; set; } = L4Protocol.Tcp;

    /// <summary>External port to open on the ingress LoadBalancer (operator-chosen, unique per cluster+protocol).</summary>
    public int ExternalPort { get; set; }
    public required string ServiceName { get; set; }
    public int ServicePort { get; set; }
    public bool IsEnabled { get; set; } = true;

    /// <summary>False = observe only, never applied/reconciled by EntKube (ownership stays external).</summary>
    public bool IsManaged { get; set; } = true;
}

/// <summary>
/// Manages app-level raw L4 (TCP/UDP) routes — exposes a customer application's port through the
/// cluster's dedicated Istio L4 ingress gateway. Each route maps one external LoadBalancer port to
/// one backend Service:port and produces a Gateway API TCPRoute or UDPRoute; the shared per-cluster
/// L4 Gateway (one listener per port) is (re)generated by KubernetesOperationsService on apply.
/// </summary>
public class AppL4RouteService(
    IDbContextFactory<ApplicationDbContext> dbFactory,
    ILogger<AppL4RouteService> logger)
{
    /// <summary>
    /// Ports reserved by Istio's auto-provisioned gateway infrastructure (status/readiness,
    /// xDS, envoy admin, east-west). Opening a listener on these would clash with the gateway
    /// pod itself, so they are rejected.
    /// </summary>
    private static readonly HashSet<int> ReservedPorts = [15000, 15001, 15006, 15008, 15020, 15021, 15090, 15012, 15443];

    public async Task<List<AppL4Route>> GetRoutesForAppAsync(Guid appId, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        return await db.AppL4Routes
            .Include(r => r.AppDeployment)
                .ThenInclude(d => d.Environment)
            .Where(r => r.AppId == appId)
            .OrderBy(r => r.Protocol)
            .ThenBy(r => r.ExternalPort)
            .ToListAsync(ct);
    }

    public async Task<List<AppL4Route>> GetRoutesForCustomerAsync(Guid customerId, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        return await db.AppL4Routes
            .Include(r => r.AppDeployment)
                .ThenInclude(d => d.App)
            .Include(r => r.AppDeployment)
                .ThenInclude(d => d.Environment)
            .Where(r => r.AppDeployment.App.CustomerId == customerId && r.IsEnabled)
            .OrderBy(r => r.AppDeployment.App.Name)
            .ThenBy(r => r.Protocol)
            .ThenBy(r => r.ExternalPort)
            .ToListAsync(ct);
    }

    public async Task<AppL4Route> AddRouteAsync(
        Guid appId, Guid deploymentId, AppL4RouteRequest request, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        AppDeployment deployment = await db.AppDeployments
            .Include(d => d.Cluster)
                .ThenInclude(c => c.Components)
            .FirstOrDefaultAsync(d => d.Id == deploymentId, ct)
            ?? throw new InvalidOperationException("Deployment not found.");

        ValidatePorts(request);

        if (ExternalRouteService.ResolveGatewayClass(deployment.Cluster.Components) != "istio")
            throw new InvalidOperationException(
                "L4 (TCP/UDP) routes require an Istio ingress gateway on this cluster. This cluster does not have Istio installed.");

        await EnsurePortFreeAsync(db, deployment.ClusterId, request.Protocol, request.ExternalPort, excludeRouteId: null, ct);

        (string gatewayName, string gatewayNamespace) =
            ExternalRouteService.ResolveL4Gateway(deployment.Cluster.Components);

        AppL4Route route = new()
        {
            Id = Guid.NewGuid(),
            AppId = appId,
            AppDeploymentId = deploymentId,
            Protocol = request.Protocol,
            ExternalPort = request.ExternalPort,
            ServiceName = request.ServiceName.Trim(),
            ServicePort = request.ServicePort,
            GatewayName = gatewayName,
            GatewayNamespace = gatewayNamespace,
            IsEnabled = request.IsEnabled,
            IsManaged = request.IsManaged
        };

        db.AppL4Routes.Add(route);
        await db.SaveChangesAsync(ct);

        logger.LogInformation(
            "L4 route {Protocol} :{ExternalPort} → {Service}:{ServicePort} added to app {AppId}",
            route.Protocol, route.ExternalPort, route.ServiceName, route.ServicePort, appId);

        return route;
    }

    public async Task UpdateRouteAsync(Guid routeId, AppL4RouteRequest request, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        AppL4Route route = await db.AppL4Routes
            .Include(r => r.AppDeployment)
            .FirstOrDefaultAsync(r => r.Id == routeId, ct)
            ?? throw new InvalidOperationException("L4 route not found.");

        ValidatePorts(request);
        await EnsurePortFreeAsync(db, route.AppDeployment.ClusterId, request.Protocol, request.ExternalPort, excludeRouteId: routeId, ct);

        route.Protocol = request.Protocol;
        route.ExternalPort = request.ExternalPort;
        route.ServiceName = request.ServiceName.Trim();
        route.ServicePort = request.ServicePort;
        route.IsEnabled = request.IsEnabled;
        route.IsManaged = request.IsManaged;
        route.ClusterAppliedAt = null; // route changed — must be re-applied

        await db.SaveChangesAsync(ct);
    }

    public async Task DeleteRouteAsync(Guid routeId, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        AppL4Route route = await db.AppL4Routes.FirstOrDefaultAsync(r => r.Id == routeId, ct)
            ?? throw new InvalidOperationException("L4 route not found.");

        db.AppL4Routes.Remove(route);
        await db.SaveChangesAsync(ct);

        logger.LogInformation("L4 route {RouteId} deleted", routeId);
    }

    /// <summary>Generates the TCPRoute/UDPRoute manifest for a route (for preview / manual apply).</summary>
    public async Task<string> GenerateManifestYamlAsync(Guid routeId, CancellationToken ct = default)
    {
        using ApplicationDbContext db = dbFactory.CreateDbContext();

        AppL4Route route = await db.AppL4Routes
            .Include(r => r.AppDeployment)
            .FirstOrDefaultAsync(r => r.Id == routeId, ct)
            ?? throw new InvalidOperationException("L4 route not found.");

        return GenerateRouteYaml(route, route.AppDeployment.Namespace);
    }

    /// <summary>
    /// Generates a Gateway API TCPRoute or UDPRoute (per <see cref="AppL4Route.Protocol"/>) that
    /// attaches to the dedicated L4 Gateway's listener for this port and forwards raw traffic to the
    /// backend Service. The route lives in the backend namespace so its backendRef needs no
    /// ReferenceGrant; the parentRef is cross-namespace (allowed because the listener permits routes
    /// from All namespaces).
    /// </summary>
    public static string GenerateRouteYaml(AppL4Route route, string backendNamespace)
    {
        string kind = RouteKind(route.Protocol);          // TCPRoute | UDPRoute
        string listener = ExternalRouteService.L4ListenerName(route.Protocol, route.ExternalPort);
        string name = $"{route.ServiceName}-{listener}";

        return
            $"apiVersion: gateway.networking.k8s.io/v1alpha2\n" +
            $"kind: {kind}\n" +
            $"metadata:\n" +
            $"  name: {name}\n" +
            $"  namespace: {backendNamespace}\n" +
            $"spec:\n" +
            $"  parentRefs:\n" +
            $"    - name: {route.GatewayName}\n" +
            $"      namespace: {route.GatewayNamespace}\n" +
            $"      sectionName: {listener}\n" +
            $"  rules:\n" +
            $"    - backendRefs:\n" +
            $"        - name: {route.ServiceName}\n" +
            $"          port: {route.ServicePort}";
    }

    /// <summary>The TCPRoute/UDPRoute resource name for a route (used when deleting from the cluster).</summary>
    public static string RouteResourceName(AppL4Route route)
        => $"{route.ServiceName}-{ExternalRouteService.L4ListenerName(route.Protocol, route.ExternalPort)}";

    /// <summary>Gateway API kind for a protocol.</summary>
    public static string RouteKind(L4Protocol protocol) => protocol == L4Protocol.Udp ? "UDPRoute" : "TCPRoute";

    /// <summary>Cluster-scoped resource type used for kubectl delete (disambiguated by group).</summary>
    public static string RouteResourceType(L4Protocol protocol)
        => protocol == L4Protocol.Udp ? "udproute.gateway.networking.k8s.io" : "tcproute.gateway.networking.k8s.io";

    /// <summary>Gateway API CRD name that must exist for a protocol.</summary>
    public static string RouteCrdName(L4Protocol protocol)
        => protocol == L4Protocol.Udp ? "udproutes.gateway.networking.k8s.io" : "tcproutes.gateway.networking.k8s.io";

    private static void ValidatePorts(AppL4RouteRequest request)
    {
        if (request.ExternalPort is < 1 or > 65535)
            throw new InvalidOperationException("External port must be between 1 and 65535.");

        if (ReservedPorts.Contains(request.ExternalPort))
            throw new InvalidOperationException(
                $"Port {request.ExternalPort} is reserved by the Istio gateway infrastructure. Choose a different port.");

        if (request.ServicePort is < 1 or > 65535)
            throw new InvalidOperationException("Service port must be between 1 and 65535.");

        if (string.IsNullOrWhiteSpace(request.ServiceName))
            throw new InvalidOperationException("Backend service name is required.");
    }

    /// <summary>
    /// Enforces that no other route on the same cluster already claims the external port for the
    /// same protocol — L4 listeners map 1:1 to physical LoadBalancer ports and cannot be shared.
    /// TCP and UDP on the same port number are allowed (distinct listeners).
    /// </summary>
    private static async Task EnsurePortFreeAsync(
        ApplicationDbContext db, Guid clusterId, L4Protocol protocol, int port, Guid? excludeRouteId, CancellationToken ct)
    {
        bool taken = await db.AppL4Routes.AnyAsync(
            r => r.AppDeployment.ClusterId == clusterId
              && r.Protocol == protocol
              && r.ExternalPort == port
              && (excludeRouteId == null || r.Id != excludeRouteId),
            ct);

        if (taken)
            throw new InvalidOperationException(
                $"{protocol.ToString().ToUpperInvariant()} port {port} is already used by another route on this cluster. Each listener needs its own port.");
    }
}
