using System.Text;

namespace EntKube.Installer;

/// <summary>
/// Reads and writes the <c>.env</c> beside the compose file.
///
/// Reading an existing one matters more than writing a new one. Two of the values in it can never be
/// regenerated once an install has run:
///
///   VAULT__ROOTKEY      encrypts every secret in the vault. A new key does not fail loudly — the
///                       app starts, and every stored credential decrypts to nothing.
///   POSTGRES_PASSWORD   is only applied when the postgres volume is first initialised. Changing it
///                       later leaves the database on the old password and the app unable to connect.
///
/// So the installer never invents a value for a key that is already present. It loads what is there,
/// offers it as the default, and writes it back untouched unless the operator deliberately replaces
/// it. That is the whole reason this type exists rather than a template render.
/// </summary>
public sealed class EnvFile
{
    private readonly Dictionary<string, string> _values = new(StringComparer.Ordinal);

    public IReadOnlyDictionary<string, string> Values => _values;

    public bool IsEmpty => _values.Count == 0;

    public string? Get(string key) =>
        _values.TryGetValue(key, out string? value) && value.Length > 0 ? value : null;

    public void Set(string key, string? value)
    {
        if (string.IsNullOrEmpty(value))
        {
            _values.Remove(key);
        }
        else
        {
            _values[key] = value;
        }
    }

    /// <summary>
    /// Parses a dotenv file. Unknown keys are preserved: an operator may well have added settings
    /// this installer has never heard of, and dropping them on the next run would be a silent
    /// reconfiguration. Anything not recognised is carried through to the new file verbatim.
    /// </summary>
    public static EnvFile Load(string path) =>
        File.Exists(path) ? Parse(File.ReadAllText(path)) : new EnvFile();

    /// <summary>
    /// Parses dotenv content. Separate from <see cref="Load"/> because the file may have arrived
    /// over SFTP from a server rather than off this disk.
    /// </summary>
    public static EnvFile Parse(string content)
    {
        EnvFile file = new();

        foreach (string raw in content.Split('\n'))
        {
            string line = raw.Trim();

            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            int split = line.IndexOf('=');
            if (split <= 0)
            {
                continue;
            }

            string key = line[..split].Trim();
            string value = line[(split + 1)..].Trim();

            // Compose accepts quoted values; strip a matched pair so a round trip through this type
            // does not accumulate quotes on every run.
            if (value.Length >= 2
                && ((value[0] == '"' && value[^1] == '"') || (value[0] == '\'' && value[^1] == '\'')))
            {
                value = value[1..^1];
            }

            file._values[key] = value;
        }

        return file;
    }

    /// <summary>
    /// Renders the file, in the order given, with the section comments an operator will need when
    /// they come back to edit it by hand — which they will, because not every setting is worth a
    /// wizard question.
    /// </summary>
    public string Render(IReadOnlyList<EnvSection> sections)
    {
        StringBuilder sb = new();

        sb.AppendLine("# EntKube management plane — generated by entkube-install.");
        sb.AppendLine("#");
        sb.AppendLine("# Safe to edit by hand. Re-running the installer reads this file first and offers every");
        sb.AppendLine("# value back as the default, so hand edits survive; keys it does not know about are");
        sb.AppendLine("# carried through untouched.");
        sb.AppendLine("#");
        sb.AppendLine("# Treat it as a secret: it holds the vault root key and the database password.");

        HashSet<string> written = new(StringComparer.Ordinal);

        foreach (EnvSection section in sections)
        {
            List<EnvEntry> present = section.Entries
                .Where(e => _values.ContainsKey(e.Key))
                .ToList();

            if (present.Count == 0)
            {
                continue;
            }

            sb.AppendLine();
            sb.AppendLine($"# --- {section.Title} ---");

            foreach (EnvEntry entry in present)
            {
                if (entry.Comment is not null)
                {
                    foreach (string line in TextWrap.Wrap(entry.Comment, 84))
                    {
                        sb.AppendLine($"# {line}");
                    }
                }

                sb.AppendLine($"{entry.Key}={Quote(_values[entry.Key])}");
                written.Add(entry.Key);
            }
        }

        List<string> unknown = _values.Keys.Where(k => !written.Contains(k)).OrderBy(k => k, StringComparer.Ordinal).ToList();

        if (unknown.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("# --- Settings added by hand ---");
            sb.AppendLine("# Preserved from the previous .env. The installer does not manage these.");

            foreach (string key in unknown)
            {
                sb.AppendLine($"{key}={Quote(_values[key])}");
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Compose splits an unquoted value at '#', so a password containing one silently truncates —
    /// and the resulting authentication failure names neither the character nor the file.
    /// </summary>
    private static string Quote(string value) =>
        value.Length > 0 && value.IndexOfAny([' ', '#', '"', '\'', '$']) >= 0
            ? '"' + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + '"'
            : value;

    public sealed record EnvEntry(string Key, string? Comment = null);

    public sealed record EnvSection(string Title, IReadOnlyList<EnvEntry> Entries);
}
